// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "IDManager_thrift.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class IDManager_thriftHandler : virtual public IDManager_thriftIf {
 public:
  IDManager_thriftHandler() {
    // Your initialization goes here
  }

  void ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void getid(std::string& _return, const std::string& cla, const std::string& msg) {
    // Your implementation goes here
    printf("getid\n");
  }

  void getallid(std::vector<std::string> & _return, const std::string& cla) {
    // Your implementation goes here
    printf("getallid\n");
  }

};

/* 注释掉主函数，by hanzhonghua
int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<IDManager_thriftHandler> handler(new IDManager_thriftHandler());
  shared_ptr<TProcessor> processor(new IDManager_thriftProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

// */
