/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef IDManager_thrift_CONSTANTS_H
#define IDManager_thrift_CONSTANTS_H

#include "IDManager_thrift_types.h"



class IDManager_thriftConstants {
 public:
  IDManager_thriftConstants();

  int32_t INT32CONSTANT;
  std::map<std::string, std::string>  MAPCONSTANT;
};

extern const IDManager_thriftConstants g_IDManager_thrift_constants;



#endif
