/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "IDManager_thrift_constants.h"



const IDManager_thriftConstants g_IDManager_thrift_constants;

IDManager_thriftConstants::IDManager_thriftConstants() {
  INT32CONSTANT = 9853;

  MAPCONSTANT.insert(std::make_pair("hello", "world"));
  MAPCONSTANT.insert(std::make_pair("goodnight", "moon"));

}



